package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/_ControlStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public class _ControlStub extends org.omg.CORBA.portable.ObjectImpl implements org.openejb.corba.idl.CosTransactions.Control
{

  public org.openejb.corba.idl.CosTransactions.Terminator get_terminator () throws org.openejb.corba.idl.CosTransactions.Unavailable
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("get_terminator", true);
                $in = _invoke ($out);
                org.openejb.corba.idl.CosTransactions.Terminator $result = org.openejb.corba.idl.CosTransactions.TerminatorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:CosTransactions/Unavailable:1.0"))
                    throw org.openejb.corba.idl.CosTransactions.UnavailableHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return get_terminator (        );
            } finally {
                _releaseReply ($in);
            }
  } // get_terminator

  public org.openejb.corba.idl.CosTransactions.Coordinator get_coordinator () throws org.openejb.corba.idl.CosTransactions.Unavailable
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("get_coordinator", true);
                $in = _invoke ($out);
                org.openejb.corba.idl.CosTransactions.Coordinator $result = org.openejb.corba.idl.CosTransactions.CoordinatorHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:CosTransactions/Unavailable:1.0"))
                    throw org.openejb.corba.idl.CosTransactions.UnavailableHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return get_coordinator (        );
            } finally {
                _releaseReply ($in);
            }
  } // get_coordinator

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:CosTransactions/Control:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _ControlStub
