package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/ControlOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public interface ControlOperations 
{
  org.openejb.corba.idl.CosTransactions.Terminator get_terminator () throws org.openejb.corba.idl.CosTransactions.Unavailable;
  org.openejb.corba.idl.CosTransactions.Coordinator get_coordinator () throws org.openejb.corba.idl.CosTransactions.Unavailable;
} // interface ControlOperations
