package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/CurrentOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/


// Current transaction
public interface CurrentOperations  extends org.omg.CORBA.CurrentOperations
{
  void begin () throws org.openejb.corba.idl.CosTransactions.SubtransactionsUnavailable;
  void commit (boolean report_heuristics) throws org.openejb.corba.idl.CosTransactions.NoTransaction, org.openejb.corba.idl.CosTransactions.HeuristicMixed, org.openejb.corba.idl.CosTransactions.HeuristicHazard;
  void rollback () throws org.openejb.corba.idl.CosTransactions.NoTransaction;
  void rollback_only () throws org.openejb.corba.idl.CosTransactions.NoTransaction;
  org.openejb.corba.idl.CosTransactions.Status get_status ();
  String get_transaction_name ();
  void set_timeout (int seconds);
  int get_timeout ();
  org.openejb.corba.idl.CosTransactions.Control get_control ();
  org.openejb.corba.idl.CosTransactions.Control suspend ();
  void resume (org.openejb.corba.idl.CosTransactions.Control which) throws org.openejb.corba.idl.CosTransactions.InvalidControl;
} // interface CurrentOperations
