package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/HeuristicHazard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public final class HeuristicHazard extends org.omg.CORBA.UserException
{

  public HeuristicHazard ()
  {
    super(HeuristicHazardHelper.id());
  } // ctor


  public HeuristicHazard (String $reason)
  {
    super(HeuristicHazardHelper.id() + "  " + $reason);
  } // ctor

} // class HeuristicHazard
