package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/Inactive.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public final class Inactive extends org.omg.CORBA.UserException
{

  public Inactive ()
  {
    super(InactiveHelper.id());
  } // ctor


  public Inactive (String $reason)
  {
    super(InactiveHelper.id() + "  " + $reason);
  } // ctor

} // class Inactive
