package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/InvalidControl.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public final class InvalidControl extends org.omg.CORBA.UserException
{

  public InvalidControl ()
  {
    super(InvalidControlHelper.id());
  } // ctor


  public InvalidControl (String $reason)
  {
    super(InvalidControlHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidControl
