package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/NoTransaction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public final class NoTransaction extends org.omg.CORBA.UserException
{

  public NoTransaction ()
  {
    super(NoTransactionHelper.id());
  } // ctor


  public NoTransaction (String $reason)
  {
    super(NoTransactionHelper.id() + "  " + $reason);
  } // ctor

} // class NoTransaction
