package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/otid_tHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/


// Structure definitions
abstract public class otid_tHelper
{
  private static String  _id = "IDL:CosTransactions/otid_t:1.0";

  public static void insert (org.omg.CORBA.Any a, org.openejb.corba.idl.CosTransactions.otid_t that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.openejb.corba.idl.CosTransactions.otid_t extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "formatID",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[1] = new org.omg.CORBA.StructMember (
            "bqual_length",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_octet);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "tid",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.openejb.corba.idl.CosTransactions.otid_tHelper.id (), "otid_t", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.openejb.corba.idl.CosTransactions.otid_t read (org.omg.CORBA.portable.InputStream istream)
  {
    org.openejb.corba.idl.CosTransactions.otid_t value = new org.openejb.corba.idl.CosTransactions.otid_t ();
    value.formatID = istream.read_long ();
    value.bqual_length = istream.read_long ();
    int _len0 = istream.read_long ();
    value.tid = new byte[_len0];
    istream.read_octet_array (value.tid, 0, _len0);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.openejb.corba.idl.CosTransactions.otid_t value)
  {
    ostream.write_long (value.formatID);
    ostream.write_long (value.bqual_length);
    ostream.write_long (value.tid.length);
    ostream.write_octet_array (value.tid, 0, value.tid.length);
  }

}
