package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/StatusHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/


// DATATYPES
abstract public class StatusHelper
{
  private static String  _id = "IDL:CosTransactions/Status:1.0";

  public static void insert (org.omg.CORBA.Any a, org.openejb.corba.idl.CosTransactions.Status that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.openejb.corba.idl.CosTransactions.Status extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (org.openejb.corba.idl.CosTransactions.StatusHelper.id (), "Status", new String[] { "StatusActive", "StatusMarkedRollback", "StatusPrepared", "StatusCommitted", "StatusRolledBack", "StatusUnknown", "StatusNoTransaction", "StatusPreparing", "StatusCommitting", "StatusRollingBack"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.openejb.corba.idl.CosTransactions.Status read (org.omg.CORBA.portable.InputStream istream)
  {
    return org.openejb.corba.idl.CosTransactions.Status.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.openejb.corba.idl.CosTransactions.Status value)
  {
    ostream.write_long (value.value ());
  }

}
