package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/SubtransactionAwareResourceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public interface SubtransactionAwareResourceOperations  extends org.openejb.corba.idl.CosTransactions.ResourceOperations
{
  void commit_subtransaction (org.openejb.corba.idl.CosTransactions.Coordinator parent);
  void rollback_subtransaction ();
} // interface SubtransactionAwareResourceOperations
