package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/Synchronization.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/


// Inheritance from TransactionalObject is for backward compatability //
public interface Synchronization extends SynchronizationOperations, org.openejb.corba.idl.CosTransactions.TransactionalObject, org.omg.CORBA.portable.IDLEntity
{
} // interface Synchronization
