package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/SynchronizationUnavailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public final class SynchronizationUnavailable extends org.omg.CORBA.UserException
{

  public SynchronizationUnavailable ()
  {
    super(SynchronizationUnavailableHelper.id());
  } // ctor


  public SynchronizationUnavailable (String $reason)
  {
    super(SynchronizationUnavailableHelper.id() + "  " + $reason);
  } // ctor

} // class SynchronizationUnavailable
