package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/TransIdentityHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

abstract public class TransIdentityHelper
{
  private static String  _id = "IDL:CosTransactions/TransIdentity:1.0";

  public static void insert (org.omg.CORBA.Any a, org.openejb.corba.idl.CosTransactions.TransIdentity that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.openejb.corba.idl.CosTransactions.TransIdentity extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.openejb.corba.idl.CosTransactions.CoordinatorHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "coord",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.openejb.corba.idl.CosTransactions.TerminatorHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "term",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.openejb.corba.idl.CosTransactions.otid_tHelper.type ();
          _members0[2] = new org.omg.CORBA.StructMember (
            "otid",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.openejb.corba.idl.CosTransactions.TransIdentityHelper.id (), "TransIdentity", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.openejb.corba.idl.CosTransactions.TransIdentity read (org.omg.CORBA.portable.InputStream istream)
  {
    org.openejb.corba.idl.CosTransactions.TransIdentity value = new org.openejb.corba.idl.CosTransactions.TransIdentity ();
    value.coord = org.openejb.corba.idl.CosTransactions.CoordinatorHelper.read (istream);
    value.term = org.openejb.corba.idl.CosTransactions.TerminatorHelper.read (istream);
    value.otid = org.openejb.corba.idl.CosTransactions.otid_tHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.openejb.corba.idl.CosTransactions.TransIdentity value)
  {
    org.openejb.corba.idl.CosTransactions.CoordinatorHelper.write (ostream, value.coord);
    org.openejb.corba.idl.CosTransactions.TerminatorHelper.write (ostream, value.term);
    org.openejb.corba.idl.CosTransactions.otid_tHelper.write (ostream, value.otid);
  }

}
