package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/TransIdentity.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public final class TransIdentity implements org.omg.CORBA.portable.IDLEntity
{
  public org.openejb.corba.idl.CosTransactions.Coordinator coord = null;
  public org.openejb.corba.idl.CosTransactions.Terminator term = null;
  public org.openejb.corba.idl.CosTransactions.otid_t otid = null;

  public TransIdentity ()
  {
  } // ctor

  public TransIdentity (org.openejb.corba.idl.CosTransactions.Coordinator _coord, org.openejb.corba.idl.CosTransactions.Terminator _term, org.openejb.corba.idl.CosTransactions.otid_t _otid)
  {
    coord = _coord;
    term = _term;
    otid = _otid;
  } // ctor

} // class TransIdentity
