package org.openejb.corba.idl.CosTSInteroperation;


/**
* org/apache/geronimo/interop/CosTSInteroperation/TransactionPolicyComponent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTSInteroperation.idl
* Saturday, March 12, 2005 1:30:02 PM EST
*/

public final class TransactionPolicyComponent implements org.omg.CORBA.portable.IDLEntity
{
  public short tpv = (short)0;

  public TransactionPolicyComponent ()
  {
  } // ctor

  public TransactionPolicyComponent (short _tpv)
  {
    tpv = _tpv;
  } // ctor

} // class TransactionPolicyComponent
