package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/CoordinatorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public interface CoordinatorOperations 
{
  org.openejb.corba.idl.CosTransactions.Status get_status ();
  org.openejb.corba.idl.CosTransactions.Status get_parent_status ();
  org.openejb.corba.idl.CosTransactions.Status get_top_level_status ();
  boolean is_same_transaction (org.openejb.corba.idl.CosTransactions.Coordinator tc);
  boolean is_related_transaction (org.openejb.corba.idl.CosTransactions.Coordinator tc);
  boolean is_ancestor_transaction (org.openejb.corba.idl.CosTransactions.Coordinator tc);
  boolean is_descendant_transaction (org.openejb.corba.idl.CosTransactions.Coordinator tc);
  boolean is_top_level_transaction ();
  int hash_transaction ();
  int hash_top_level_tran ();
  org.openejb.corba.idl.CosTransactions.RecoveryCoordinator register_resource (org.openejb.corba.idl.CosTransactions.Resource r) throws org.openejb.corba.idl.CosTransactions.Inactive;
  void register_synchronization (org.openejb.corba.idl.CosTransactions.Synchronization sync) throws org.openejb.corba.idl.CosTransactions.Inactive, org.openejb.corba.idl.CosTransactions.SynchronizationUnavailable;
  void register_subtran_aware (org.openejb.corba.idl.CosTransactions.SubtransactionAwareResource r) throws org.openejb.corba.idl.CosTransactions.Inactive, org.openejb.corba.idl.CosTransactions.NotSubtransaction;
  void rollback_only () throws org.openejb.corba.idl.CosTransactions.Inactive;
  String get_transaction_name ();
  org.openejb.corba.idl.CosTransactions.Control create_subtransaction () throws org.openejb.corba.idl.CosTransactions.SubtransactionsUnavailable, org.openejb.corba.idl.CosTransactions.Inactive;
  org.openejb.corba.idl.CosTransactions.PropagationContext get_txcontext () throws org.openejb.corba.idl.CosTransactions.Unavailable;
} // interface CoordinatorOperations
