package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/HeuristicRollback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public final class HeuristicRollback extends org.omg.CORBA.UserException
{

  public HeuristicRollback ()
  {
    super(HeuristicRollbackHelper.id());
  } // ctor


  public HeuristicRollback (String $reason)
  {
    super(HeuristicRollbackHelper.id() + "  " + $reason);
  } // ctor

} // class HeuristicRollback
