package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/HeuristicCommit.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public final class HeuristicCommit extends org.omg.CORBA.UserException
{

  public HeuristicCommit ()
  {
    super(HeuristicCommitHelper.id());
  } // ctor


  public HeuristicCommit (String $reason)
  {
    super(HeuristicCommitHelper.id() + "  " + $reason);
  } // ctor

} // class HeuristicCommit
