package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/otid_t.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/


// Structure definitions
public final class otid_t implements org.omg.CORBA.portable.IDLEntity
{
  public int formatID = (int)0;

  /*format identifier. 0 is OSI TP */
  public int bqual_length = (int)0;
  public byte tid[] = null;

  public otid_t ()
  {
  } // ctor

  public otid_t (int _formatID, int _bqual_length, byte[] _tid)
  {
    formatID = _formatID;
    bqual_length = _bqual_length;
    tid = _tid;
  } // ctor

} // class otid_t
