package org.openejb.corba.idl.CosTransactions;

/**
* org/apache/geronimo/interop/CosTransactions/otid_tHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/


// Structure definitions
public final class otid_tHolder implements org.omg.CORBA.portable.Streamable
{
  public org.openejb.corba.idl.CosTransactions.otid_t value = null;

  public otid_tHolder ()
  {
  }

  public otid_tHolder (org.openejb.corba.idl.CosTransactions.otid_t initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.openejb.corba.idl.CosTransactions.otid_tHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.openejb.corba.idl.CosTransactions.otid_tHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.openejb.corba.idl.CosTransactions.otid_tHelper.type ();
  }

}
