package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/PropagationContext.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public final class PropagationContext implements org.omg.CORBA.portable.IDLEntity
{
  public int timeout = (int)0;
  public org.openejb.corba.idl.CosTransactions.TransIdentity current = null;
  public org.openejb.corba.idl.CosTransactions.TransIdentity parents[] = null;
  public org.omg.CORBA.Any implementation_specific_data = null;

  public PropagationContext ()
  {
  } // ctor

  public PropagationContext (int _timeout, org.openejb.corba.idl.CosTransactions.TransIdentity _current, org.openejb.corba.idl.CosTransactions.TransIdentity[] _parents, org.omg.CORBA.Any _implementation_specific_data)
  {
    timeout = _timeout;
    current = _current;
    parents = _parents;
    implementation_specific_data = _implementation_specific_data;
  } // ctor

} // class PropagationContext
