package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/PropagationContextHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

abstract public class PropagationContextHelper
{
  private static String  _id = "IDL:CosTransactions/PropagationContext:1.0";

  public static void insert (org.omg.CORBA.Any a, org.openejb.corba.idl.CosTransactions.PropagationContext that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.openejb.corba.idl.CosTransactions.PropagationContext extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_ulong);
          _members0[0] = new org.omg.CORBA.StructMember (
            "timeout",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.openejb.corba.idl.CosTransactions.TransIdentityHelper.type ();
          _members0[1] = new org.omg.CORBA.StructMember (
            "current",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.openejb.corba.idl.CosTransactions.TransIdentityHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "parents",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_any);
          _members0[3] = new org.omg.CORBA.StructMember (
            "implementation_specific_data",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (org.openejb.corba.idl.CosTransactions.PropagationContextHelper.id (), "PropagationContext", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.openejb.corba.idl.CosTransactions.PropagationContext read (org.omg.CORBA.portable.InputStream istream)
  {
    org.openejb.corba.idl.CosTransactions.PropagationContext value = new org.openejb.corba.idl.CosTransactions.PropagationContext ();
    value.timeout = istream.read_ulong ();
    value.current = org.openejb.corba.idl.CosTransactions.TransIdentityHelper.read (istream);
    int _len0 = istream.read_long ();
    value.parents = new org.openejb.corba.idl.CosTransactions.TransIdentity[_len0];
    for (int _o1 = 0;_o1 < value.parents.length; ++_o1)
      value.parents[_o1] = org.openejb.corba.idl.CosTransactions.TransIdentityHelper.read (istream);
    value.implementation_specific_data = istream.read_any ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.openejb.corba.idl.CosTransactions.PropagationContext value)
  {
    ostream.write_ulong (value.timeout);
    org.openejb.corba.idl.CosTransactions.TransIdentityHelper.write (ostream, value.current);
    ostream.write_long (value.parents.length);
    for (int _i0 = 0;_i0 < value.parents.length; ++_i0)
      org.openejb.corba.idl.CosTransactions.TransIdentityHelper.write (ostream, value.parents[_i0]);
    ostream.write_any (value.implementation_specific_data);
  }

}
