package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/ResourceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public interface ResourceOperations 
{
  org.openejb.corba.idl.CosTransactions.Vote prepare () throws org.openejb.corba.idl.CosTransactions.HeuristicMixed, org.openejb.corba.idl.CosTransactions.HeuristicHazard;
  void rollback () throws org.openejb.corba.idl.CosTransactions.HeuristicCommit, org.openejb.corba.idl.CosTransactions.HeuristicMixed, org.openejb.corba.idl.CosTransactions.HeuristicHazard;
  void commit () throws org.openejb.corba.idl.CosTransactions.NotPrepared, org.openejb.corba.idl.CosTransactions.HeuristicRollback, org.openejb.corba.idl.CosTransactions.HeuristicMixed, org.openejb.corba.idl.CosTransactions.HeuristicHazard;
  void commit_one_phase () throws org.openejb.corba.idl.CosTransactions.HeuristicHazard;
  void forget ();
} // interface ResourceOperations
