package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/Status.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/


// DATATYPES
public class Status implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 10;
  private static org.openejb.corba.idl.CosTransactions.Status[] __array = new org.openejb.corba.idl.CosTransactions.Status [__size];

  public static final int _StatusActive = 0;
  public static final org.openejb.corba.idl.CosTransactions.Status StatusActive = new org.openejb.corba.idl.CosTransactions.Status(_StatusActive);
  public static final int _StatusMarkedRollback = 1;
  public static final org.openejb.corba.idl.CosTransactions.Status StatusMarkedRollback = new org.openejb.corba.idl.CosTransactions.Status(_StatusMarkedRollback);
  public static final int _StatusPrepared = 2;
  public static final org.openejb.corba.idl.CosTransactions.Status StatusPrepared = new org.openejb.corba.idl.CosTransactions.Status(_StatusPrepared);
  public static final int _StatusCommitted = 3;
  public static final org.openejb.corba.idl.CosTransactions.Status StatusCommitted = new org.openejb.corba.idl.CosTransactions.Status(_StatusCommitted);
  public static final int _StatusRolledBack = 4;
  public static final org.openejb.corba.idl.CosTransactions.Status StatusRolledBack = new org.openejb.corba.idl.CosTransactions.Status(_StatusRolledBack);
  public static final int _StatusUnknown = 5;
  public static final org.openejb.corba.idl.CosTransactions.Status StatusUnknown = new org.openejb.corba.idl.CosTransactions.Status(_StatusUnknown);
  public static final int _StatusNoTransaction = 6;
  public static final org.openejb.corba.idl.CosTransactions.Status StatusNoTransaction = new org.openejb.corba.idl.CosTransactions.Status(_StatusNoTransaction);
  public static final int _StatusPreparing = 7;
  public static final org.openejb.corba.idl.CosTransactions.Status StatusPreparing = new org.openejb.corba.idl.CosTransactions.Status(_StatusPreparing);
  public static final int _StatusCommitting = 8;
  public static final org.openejb.corba.idl.CosTransactions.Status StatusCommitting = new org.openejb.corba.idl.CosTransactions.Status(_StatusCommitting);
  public static final int _StatusRollingBack = 9;
  public static final org.openejb.corba.idl.CosTransactions.Status StatusRollingBack = new org.openejb.corba.idl.CosTransactions.Status(_StatusRollingBack);

  public int value ()
  {
    return __value;
  }

  public static org.openejb.corba.idl.CosTransactions.Status from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Status (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Status
