package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/SubtransactionsUnavailable.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public final class SubtransactionsUnavailable extends org.omg.CORBA.UserException
{

  public SubtransactionsUnavailable ()
  {
    super(SubtransactionsUnavailableHelper.id());
  } // ctor


  public SubtransactionsUnavailable (String $reason)
  {
    super(SubtransactionsUnavailableHelper.id() + "  " + $reason);
  } // ctor

} // class SubtransactionsUnavailable
