package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/TransactionalObjectOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/


// TransactionalObject has been deprecated. See 10.3.10.
public interface TransactionalObjectOperations 
{
} // interface TransactionalObjectOperations
