package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/TransactionPolicyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

abstract public class TransactionPolicyHelper
{
  private static String  _id = "IDL:CosTransactions/TransactionPolicy:1.0";

  public static void insert (org.omg.CORBA.Any a, org.openejb.corba.idl.CosTransactions.TransactionPolicy that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static org.openejb.corba.idl.CosTransactions.TransactionPolicy extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (org.openejb.corba.idl.CosTransactions.TransactionPolicyHelper.id (), "TransactionPolicy");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static org.openejb.corba.idl.CosTransactions.TransactionPolicy read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TransactionPolicyStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, org.openejb.corba.idl.CosTransactions.TransactionPolicy value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static org.openejb.corba.idl.CosTransactions.TransactionPolicy narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof org.openejb.corba.idl.CosTransactions.TransactionPolicy)
      return (org.openejb.corba.idl.CosTransactions.TransactionPolicy)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      org.openejb.corba.idl.CosTransactions._TransactionPolicyStub stub = new org.openejb.corba.idl.CosTransactions._TransactionPolicyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
