package org.openejb.corba.idl.CosTransactions;


/**
* org/apache/geronimo/interop/CosTransactions/Vote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTransactions.idl
* Saturday, March 12, 2005 1:30:01 PM EST
*/

public class Vote implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static org.openejb.corba.idl.CosTransactions.Vote[] __array = new org.openejb.corba.idl.CosTransactions.Vote [__size];

  public static final int _VoteCommit = 0;
  public static final org.openejb.corba.idl.CosTransactions.Vote VoteCommit = new org.openejb.corba.idl.CosTransactions.Vote(_VoteCommit);
  public static final int _VoteRollback = 1;
  public static final org.openejb.corba.idl.CosTransactions.Vote VoteRollback = new org.openejb.corba.idl.CosTransactions.Vote(_VoteRollback);
  public static final int _VoteReadOnly = 2;
  public static final org.openejb.corba.idl.CosTransactions.Vote VoteReadOnly = new org.openejb.corba.idl.CosTransactions.Vote(_VoteReadOnly);

  public int value ()
  {
    return __value;
  }

  public static org.openejb.corba.idl.CosTransactions.Vote from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected Vote (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class Vote
