package org.openejb.corba.idl.CosTSInteroperation;


/**
* org/apache/geronimo/interop/CosTSInteroperation/TAG_OTS_POLICY.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTSInteroperation.idl
* Saturday, March 12, 2005 1:30:02 PM EST
*/

public interface TAG_OTS_POLICY
{
  public static final int value = (int)(31);
}
