package org.openejb.corba.idl.CosTSInteroperation;

/**
* org/apache/geronimo/interop/CosTSInteroperation/TransactionPolicyComponentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from C:/dev/corba/geronimo/trunk/modules/interop/src/idl/CosTSInteroperation.idl
* Saturday, March 12, 2005 1:30:02 PM EST
*/

public final class TransactionPolicyComponentHolder implements org.omg.CORBA.portable.Streamable
{
  public org.openejb.corba.idl.CosTSInteroperation.TransactionPolicyComponent value = null;

  public TransactionPolicyComponentHolder ()
  {
  }

  public TransactionPolicyComponentHolder (org.openejb.corba.idl.CosTSInteroperation.TransactionPolicyComponent initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = org.openejb.corba.idl.CosTSInteroperation.TransactionPolicyComponentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    org.openejb.corba.idl.CosTSInteroperation.TransactionPolicyComponentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return org.openejb.corba.idl.CosTSInteroperation.TransactionPolicyComponentHelper.type ();
  }

}
